version: '2.3'

services:
  niino-handbook:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: niino-handbook
    image: niino-handbook
    volumes: 
      - $PWD:/workspace
    working_dir: /workspace
    tty: true
    command: /bin/bash
networks:
    default:
        external:
            name: niino-network